### ISSUE TITLE
[Bug-gmx_MMPBSA]: Alanine scanning

### ISSUE THREAD

**Issue by aptamer1234** [Valdes-Tresanco-MS/gmx_MMPBSA#298]
### Bug summary

I use the alanine scanning program in the example, but the ligands and receptors cannot be recognized. Do I need to create the PDB files of the ligands and receptors by myself?

### Terminal output

```bash
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 21: 'GMXMMPBSA_LIG'
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Changing the Complex residues name format from GROMACS to AMBER...
[INFO   ] Changing the Receptor residues name format from GROMACS to AMBER...
[INFO   ] Changing the Ligand residues name format from GROMACS to AMBER...
[INFO   ] Splitting  receptor and ligand in PDB files..
[ERROR  ] MMPBSA_Error For decomposition analysis, you most define residues for both receptor and ligand!.
           Check the gmx_MMPBSA.log file to report the problem.
```

### gmx_MMPBSA.log

[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 21: 'GMXMMPBSA_LIG'
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Changing the Complex residues name format from GROMACS to AMBER...
[INFO   ] Changing the Receptor residues name format from GROMACS to AMBER...
[INFO   ] Changing the Ligand residues name format from GROMACS to AMBER...
[INFO   ] Splitting  receptor and ligand in PDB files..
[ERROR  ] MMPBSA_Error For decomposition analysis, you most define residues for both receptor and ligand!.
           Check the gmx_MMPBSA.log file to report the problem.

### Operating system

Ubuntu22.04

### gmx_MMPBSA Version

gmx_MMPBSA_test v1.5.6+30.g0c3c6ec based on MMPBSA version 16.0

### Python version

python 3.9

### Installation

from source (.tar.gz)

**Comment by marioernestovaldes** [comment]
Seems like the groups defined don't contain the right atoms. could you please attached the .log file?

**Comment by aptamer1234** [comment]
[INFO   ] Starting gmx_MMPBSA v1.5.6+30.g0c3c6ec
[DEBUG  ] WDIR          : /media/b1612/0b343021-fe7b-40e9-999b-fdf4f587092d/scFv-pp/gmx_MMPBSA_test/examples/Alanine_scanning
[DEBUG  ] AMBERHOME     : /home/b1612/miniconda3/envs/gmxMMPBSA
[DEBUG  ] PYTHON EXE    : /home/b1612/miniconda3/envs/gmxMMPBSA/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) [GCC 10.3.0]
[DEBUG  ] MPI           : /home/b1612/miniconda3/envs/gmxMMPBSA/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.3+10.ga195c7e
[DEBUG  ] OS PLATFORM   : Linux-5.15.0-52-generic-x86_64-with-glibc2.35
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Sample input file for Alanine scanning
[DEBUG  ] |#This input file is meant to show only that gmx_MMPBSA works. Although, we tried to use the input files as recommended in the
[DEBUG  ] |#Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the parameters
[DEBUG  ] |#according to what is better for your system.
[DEBUG  ] |
[DEBUG  ] |&general
[DEBUG  ] |sys_name="Alanine_Scanning",
[DEBUG  ] |startframe=1,
[DEBUG  ] |endframe=10,
[DEBUG  ] |forcefields="leaprc.protein.ff14SB",
[DEBUG  ] |PBRadii=4,
[DEBUG  ] |/
[DEBUG  ] |&gb
[DEBUG  ] |igb=8, saltcon=0.150,
[DEBUG  ] |/
[DEBUG  ] |&alanine_scanning
[DEBUG  ] |mutant='ALA', mutant_res='A:23', cas_intdiel=1
[DEBUG  ] |/
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/b1612/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/b1612/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/b1612/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/b1612/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[DEBUG  ] Running command: echo name 20 GMXMMPBSA_REC\n name 21 GMXMMPBSA_LIG\n  20 | 21\n q\n | /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx
[DEBUG  ]                 :-) GROMACS - gmx make_ndx, 2021.3-bioconda (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Andrey Alekseenko              Emile Apol              Rossen Apostolov     
[DEBUG  ]          Paul Bauer           Herman J.C. Berendsen           Par Bjelkmar       
[DEBUG  ]        Christian Blau           Viacheslav Bolnykh             Kevin Boyd        
[DEBUG  ]      Aldert van Buuren           Rudi van Drunen             Anton Feenstra      
[DEBUG  ]     Gilles Gouaillardet             Alan Gray               Gerrit Groenhof      
[DEBUG  ]        Anca Hamuraru            Vincent Hindriksen          M. Eric Irrgang      
[DEBUG  ]       Aleksei Iupinov           Christoph Junghans             Joe Jordan        
[DEBUG  ]     Dimitrios Karkoulis            Peter Kasson                Jiri Kraus        
[DEBUG  ]       Carsten Kutzner              Per Larsson              Justin A. Lemkul     
[DEBUG  ]        Viveca Lindahl            Magnus Lundborg             Erik Marklund       
[DEBUG  ]         Pascal Merz             Pieter Meulenhoff            Teemu Murtola       
[DEBUG  ]         Szilard Pall               Sander Pronk              Roland Schulz       
[DEBUG  ]        Michael Shirts            Alexey Shvetsov             Alfons Sijbers      
[DEBUG  ]        Peter Tieleman              Jon Vincent              Teemu Virolainen     
[DEBUG  ]      Christian Wennberg            Maarten Wolf              Artem Zhmurov       
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx make_ndx, version 2021.3-bioconda
[DEBUG  ] Executable:   /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /home/b1612/miniconda3/envs/gmxMMPBSA
[DEBUG  ] Working dir:  /media/b1612/0b343021-fe7b-40e9-999b-fdf4f587092d/scFv-pp/gmx_MMPBSA_test/examples/Alanine_scanning
[DEBUG  ] Command line:
[DEBUG  ]   gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "There is no reason for any individual to have a computer in his home." (Ken Olsen, head of Digital Equipment Corp.)
[DEBUG  ] 
[DEBUG  ] Going to read 1 old index file(s)
[DEBUG  ] Counted atom numbers up to 11480 in index file
[DEBUG  ] 
[DEBUG  ]   0 System              : 11480 atoms
[DEBUG  ]   1 Protein             :   608 atoms
[DEBUG  ]   2 Protein-H           :   319 atoms
[DEBUG  ]   3 C-alpha             :    39 atoms
[DEBUG  ]   4 Backbone            :   117 atoms
[DEBUG  ]   5 MainChain           :   158 atoms
[DEBUG  ]   6 MainChain+Cb        :   194 atoms
[DEBUG  ]   7 MainChain+H         :   196 atoms
[DEBUG  ]   8 SideChain           :   412 atoms
[DEBUG  ]   9 SideChain-H         :   161 atoms
[DEBUG  ]  10 Prot-Masses         :   608 atoms
[DEBUG  ]  11 non-Protein         : 10872 atoms
[DEBUG  ]  12 Ion                 :    21 atoms
[DEBUG  ]  13 Na+                 :    11 atoms
[DEBUG  ]  14 Cl-                 :    10 atoms
[DEBUG  ]  15 TP3                 : 10851 atoms
[DEBUG  ]  16 Other               : 10851 atoms
[DEBUG  ]  17 Na+                 :    11 atoms
[DEBUG  ]  18 Cl-                 :    10 atoms
[DEBUG  ]  19 TP3                 : 10851 atoms
[DEBUG  ]  20 Protein_chain1      :   478 atoms
[DEBUG  ]  21 Protein_chain2      :   130 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] Copied index group 20 'GMXMMPBSA_REC'
[DEBUG  ] Copied index group 21 'GMXMMPBSA_LIG'
[DEBUG  ] Merged two groups with OR: 478 130 -> 608
[DEBUG  ] 
[DEBUG  ]  22 GMXMMPBSA_REC_GMXMMPBSA_LIG:   608 atoms
[DEBUG  ] 
[DEBUG  ] > 
[INFO   ] Normal Complex: Saving group 20_21 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[DEBUG  ] Running command: echo GMXMMPBSA_REC_GMXMMPBSA_LIG | /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                  :-) GROMACS - gmx trjconv, 2021.3-bioconda (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Andrey Alekseenko              Emile Apol              Rossen Apostolov     
[DEBUG  ]          Paul Bauer           Herman J.C. Berendsen           Par Bjelkmar       
[DEBUG  ]        Christian Blau           Viacheslav Bolnykh             Kevin Boyd        
[DEBUG  ]      Aldert van Buuren           Rudi van Drunen             Anton Feenstra      
[DEBUG  ]     Gilles Gouaillardet             Alan Gray               Gerrit Groenhof      
[DEBUG  ]        Anca Hamuraru            Vincent Hindriksen          M. Eric Irrgang      
[DEBUG  ]       Aleksei Iupinov           Christoph Junghans             Joe Jordan        
[DEBUG  ]     Dimitrios Karkoulis            Peter Kasson                Jiri Kraus        
[DEBUG  ]       Carsten Kutzner              Per Larsson              Justin A. Lemkul     
[DEBUG  ]        Viveca Lindahl            Magnus Lundborg             Erik Marklund       
[DEBUG  ]         Pascal Merz             Pieter Meulenhoff            Teemu Murtola       
[DEBUG  ]         Szilard Pall               Sander Pronk              Roland Schulz       
[DEBUG  ]        Michael Shirts            Alexey Shvetsov             Alfons Sijbers      
[DEBUG  ]        Peter Tieleman              Jon Vincent              Teemu Virolainen     
[DEBUG  ]      Christian Wennberg            Maarten Wolf              Artem Zhmurov       
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx trjconv, version 2021.3-bioconda
[DEBUG  ] Executable:   /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /home/b1612/miniconda3/envs/gmxMMPBSA
[DEBUG  ] Working dir:  /media/b1612/0b343021-fe7b-40e9-999b-fdf4f587092d/scFv-pp/gmx_MMPBSA_test/examples/Alanine_scanning
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Group     0 (         System) has 11480 elements
[DEBUG  ] Group     1 (        Protein) has   608 elements
[DEBUG  ] Group     2 (      Protein-H) has   319 elements
[DEBUG  ] Group     3 (        C-alpha) has    39 elements
[DEBUG  ] Group     4 (       Backbone) has   117 elements
[DEBUG  ] Group     5 (      MainChain) has   158 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has   194 elements
[DEBUG  ] Group     7 (    MainChain+H) has   196 elements
[DEBUG  ] Group     8 (      SideChain) has   412 elements
[DEBUG  ] Group     9 (    SideChain-H) has   161 elements
[DEBUG  ] Group    10 (    Prot-Masses) has   608 elements
[DEBUG  ] Group    11 (    non-Protein) has 10872 elements
[DEBUG  ] Group    12 (            Ion) has    21 elements
[DEBUG  ] Group    13 (            Na+) has    11 elements
[DEBUG  ] Group    14 (            Cl-) has    10 elements
[DEBUG  ] Group    15 (            TP3) has 10851 elements
[DEBUG  ] Group    16 (          Other) has 10851 elements
[DEBUG  ] Group    17 (            Na+) has    11 elements
[DEBUG  ] Group    18 (            Cl-) has    10 elements
[DEBUG  ] Group    19 (            TP3) has 10851 elements
[DEBUG  ] Group    20 (  GMXMMPBSA_REC) has   478 elements
[DEBUG  ] Group    21 (  GMXMMPBSA_LIG) has   130 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   608 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of com_traj.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time    1.000   
Reading frame       0 time    0.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "There is no reason for any individual to have a computer in his home." (Ken Olsen, head of Digital Equipment Corp.)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 22: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 20 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[DEBUG  ] Running command: echo 20 | /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                  :-) GROMACS - gmx trjconv, 2021.3-bioconda (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Andrey Alekseenko              Emile Apol              Rossen Apostolov     
[DEBUG  ]          Paul Bauer           Herman J.C. Berendsen           Par Bjelkmar       
[DEBUG  ]        Christian Blau           Viacheslav Bolnykh             Kevin Boyd        
[DEBUG  ]      Aldert van Buuren           Rudi van Drunen             Anton Feenstra      
[DEBUG  ]     Gilles Gouaillardet             Alan Gray               Gerrit Groenhof      
[DEBUG  ]        Anca Hamuraru            Vincent Hindriksen          M. Eric Irrgang      
[DEBUG  ]       Aleksei Iupinov           Christoph Junghans             Joe Jordan        
[DEBUG  ]     Dimitrios Karkoulis            Peter Kasson                Jiri Kraus        
[DEBUG  ]       Carsten Kutzner              Per Larsson              Justin A. Lemkul     
[DEBUG  ]        Viveca Lindahl            Magnus Lundborg             Erik Marklund       
[DEBUG  ]         Pascal Merz             Pieter Meulenhoff            Teemu Murtola       
[DEBUG  ]         Szilard Pall               Sander Pronk              Roland Schulz       
[DEBUG  ]        Michael Shirts            Alexey Shvetsov             Alfons Sijbers      
[DEBUG  ]        Peter Tieleman              Jon Vincent              Teemu Virolainen     
[DEBUG  ]      Christian Wennberg            Maarten Wolf              Artem Zhmurov       
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx trjconv, version 2021.3-bioconda
[DEBUG  ] Executable:   /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /home/b1612/miniconda3/envs/gmxMMPBSA
[DEBUG  ] Working dir:  /media/b1612/0b343021-fe7b-40e9-999b-fdf4f587092d/scFv-pp/gmx_MMPBSA_test/examples/Alanine_scanning
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Group     0 (         System) has 11480 elements
[DEBUG  ] Group     1 (        Protein) has   608 elements
[DEBUG  ] Group     2 (      Protein-H) has   319 elements
[DEBUG  ] Group     3 (        C-alpha) has    39 elements
[DEBUG  ] Group     4 (       Backbone) has   117 elements
[DEBUG  ] Group     5 (      MainChain) has   158 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has   194 elements
[DEBUG  ] Group     7 (    MainChain+H) has   196 elements
[DEBUG  ] Group     8 (      SideChain) has   412 elements
[DEBUG  ] Group     9 (    SideChain-H) has   161 elements
[DEBUG  ] Group    10 (    Prot-Masses) has   608 elements
[DEBUG  ] Group    11 (    non-Protein) has 10872 elements
[DEBUG  ] Group    12 (            Ion) has    21 elements
[DEBUG  ] Group    13 (            Na+) has    11 elements
[DEBUG  ] Group    14 (            Cl-) has    10 elements
[DEBUG  ] Group    15 (            TP3) has 10851 elements
[DEBUG  ] Group    16 (          Other) has 10851 elements
[DEBUG  ] Group    17 (            Na+) has    11 elements
[DEBUG  ] Group    18 (            Cl-) has    10 elements
[DEBUG  ] Group    19 (            TP3) has 10851 elements
[DEBUG  ] Group    20 (  GMXMMPBSA_REC) has   478 elements
[DEBUG  ] Group    21 (  GMXMMPBSA_LIG) has   130 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   608 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of com_traj.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time    1.000   
Reading frame       0 time    0.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "There is no reason for any individual to have a computer in his home." (Ken Olsen, head of Digital Equipment Corp.)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 20: 'GMXMMPBSA_REC'
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 21 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[DEBUG  ] Running command: echo 21 | /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                  :-) GROMACS - gmx trjconv, 2021.3-bioconda (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Andrey Alekseenko              Emile Apol              Rossen Apostolov     
[DEBUG  ]          Paul Bauer           Herman J.C. Berendsen           Par Bjelkmar       
[DEBUG  ]        Christian Blau           Viacheslav Bolnykh             Kevin Boyd        
[DEBUG  ]      Aldert van Buuren           Rudi van Drunen             Anton Feenstra      
[DEBUG  ]     Gilles Gouaillardet             Alan Gray               Gerrit Groenhof      
[DEBUG  ]        Anca Hamuraru            Vincent Hindriksen          M. Eric Irrgang      
[DEBUG  ]       Aleksei Iupinov           Christoph Junghans             Joe Jordan        
[DEBUG  ]     Dimitrios Karkoulis            Peter Kasson                Jiri Kraus        
[DEBUG  ]       Carsten Kutzner              Per Larsson              Justin A. Lemkul     
[DEBUG  ]        Viveca Lindahl            Magnus Lundborg             Erik Marklund       
[DEBUG  ]         Pascal Merz             Pieter Meulenhoff            Teemu Murtola       
[DEBUG  ]         Szilard Pall               Sander Pronk              Roland Schulz       
[DEBUG  ]        Michael Shirts            Alexey Shvetsov             Alfons Sijbers      
[DEBUG  ]        Peter Tieleman              Jon Vincent              Teemu Virolainen     
[DEBUG  ]      Christian Wennberg            Maarten Wolf              Artem Zhmurov       
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx trjconv, version 2021.3-bioconda
[DEBUG  ] Executable:   /home/b1612/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /home/b1612/miniconda3/envs/gmxMMPBSA
[DEBUG  ] Working dir:  /media/b1612/0b343021-fe7b-40e9-999b-fdf4f587092d/scFv-pp/gmx_MMPBSA_test/examples/Alanine_scanning
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f com_traj.xtc -s com.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Reading file com.tpr, VERSION 2018.3 (single precision)
[DEBUG  ] Group     0 (         System) has 11480 elements
[DEBUG  ] Group     1 (        Protein) has   608 elements
[DEBUG  ] Group     2 (      Protein-H) has   319 elements
[DEBUG  ] Group     3 (        C-alpha) has    39 elements
[DEBUG  ] Group     4 (       Backbone) has   117 elements
[DEBUG  ] Group     5 (      MainChain) has   158 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has   194 elements
[DEBUG  ] Group     7 (    MainChain+H) has   196 elements
[DEBUG  ] Group     8 (      SideChain) has   412 elements
[DEBUG  ] Group     9 (    SideChain-H) has   161 elements
[DEBUG  ] Group    10 (    Prot-Masses) has   608 elements
[DEBUG  ] Group    11 (    non-Protein) has 10872 elements
[DEBUG  ] Group    12 (            Ion) has    21 elements
[DEBUG  ] Group    13 (            Na+) has    11 elements
[DEBUG  ] Group    14 (            Cl-) has    10 elements
[DEBUG  ] Group    15 (            TP3) has 10851 elements
[DEBUG  ] Group    16 (          Other) has 10851 elements
[DEBUG  ] Group    17 (            Na+) has    11 elements
[DEBUG  ] Group    18 (            Cl-) has    10 elements
[DEBUG  ] Group    19 (            TP3) has 10851 elements
[DEBUG  ] Group    20 (  GMXMMPBSA_REC) has   478 elements
[DEBUG  ] Group    21 (  GMXMMPBSA_LIG) has   130 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   608 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of com_traj.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time    1.000   
Reading frame       0 time    0.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "There is no reason for any individual to have a computer in his home." (Ken Olsen, head of Digital Equipment Corp.)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 21: 'GMXMMPBSA_LIG'
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Changing the Complex residues name format from GROMACS to AMBER...
[INFO   ] Changing the Receptor residues name format from GROMACS to AMBER...
[INFO   ] Changing the Ligand residues name format from GROMACS to AMBER...
[INFO   ] Splitting  receptor and ligand in PDB files..
[ERROR  ] MMPBSA_Error For decomposition analysis, you most define residues for both receptor and ligand!.
           Check the gmx_MMPBSA.log file to report the problem.

**Comment by marioernestovaldes** [comment]
It's weird that it's throwing a decomposition error when you try to perform an alanine scanning... could you please send the files you're using to see what's going wrong?

**Comment by aptamer1234** [comment]
> It's weird that it's throwing a decomposition error when you try to perform an alanine scanning... could you please send the files you're using to see what's going wrong?

I‘m using the file from the example，
https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/tree/master/examples/Alanine_scanning
the command-line:
gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

**Comment by marioernestovaldes** [comment]
If youa re using the files from alanine scanning tutorial please update gmxMMPBSA AS follows:

`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA -U`

and run this command line:

`gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv`

and see if you get any error...

**Comment by aptamer1234** [comment]
> If you are using the files from the alanine scanning tutorial please update gmxMMPBSA AS follows:
> 
> `python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA -U`
> 
> and run this command line:
> 
> `gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv`
> 
> and see if you get any errors...

Thank you very much, I'll try it again

**Comment by marioernestovaldes** [comment]
Try this command 

gmx_MMPBSA -O -i [mmpbsa.in](http://mmpbsa.in/) -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

**Comment by Valdes-Tresanco-MS** [comment]
I broke the selection method fixing it for the decomposition :'(. However, I fixed it already (`v1.5.6+33.ga66c23a7`). Try to install it from GitHub 
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U
```

**Comment by aptamer1234** [comment]
![image](https://user-images.githubusercontent.com/98143626/200473598-cbb60436-2155-4ace-a9c0-bb678352eaad.png)
When I update gmxMMPBSA,I get an error.Will this affect the calculation result?
If I ignore this error and continue to run the Alanine scanning, I still get the previous error

**Comment by Valdes-Tresanco-MS** [comment]
Please follow the instructions in the documentation to create an isolated conda environment (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/#installing-gmx_mmpbsa-v15x). The problem here is that mpi4py is being installed with pip which usually ends in error. For this, it is better to install it from conda. 
Then install gmx_MMPBSA from Github as discussed above.

**Comment by aptamer1234** [comment]
> Please follow the instructions in the documentation to create an isolated conda environment (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/#installing-gmx_mmpbsa-v15x). The problem here is that mpi4py is being installed with pip which usually ends in error. For this, it is better to install it from conda. Then install gmx_MMPBSA from Github as discussed above.

Thanks for your reply! I will try to install again
