### ISSUE TITLE
[Bug-gmx_MMPBSA]: The atom 6719 in the complex index is not found in the topology file. Please check that the files are consistent.

### ISSUE THREAD

**Issue by jjjjjqt** [Valdes-Tresanco-MS/gmx_MMPBSA#489]
### Bug summary

Now there is a topology file with 6719 atoms, but gmxMMPBSA recognizes only 6718 (the 6687 atom is skipped), so that the index value cannot correspond to the topology file one by one, and finally the calculation result fails. What should I do?

### Terminal output

```bash
The atom 6719 in the complex index is not found in the topology file. Please check that the files are consistent.
```

### gmx_MMPBSA.log

[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file ../peg_md_100/peg_para_md.tpr, VERSION 2022.5 (single precision)
[DEBUG  ] Reading file ../peg_md_100/peg_para_md.tpr, VERSION 2022.5 (single precision)
[DEBUG  ] Group     0 (         System) has 56744 elements
[DEBUG  ] Group     1 (          Other) has  1717 elements
[DEBUG  ] Group     2 (            MOL) has  1591 elements
[DEBUG  ] Group     3 (            HD1) has    17 elements
[DEBUG  ] Group     4 (            HD2) has    17 elements
[DEBUG  ] Group     5 (            HE1) has    17 elements
[DEBUG  ] Group     6 (            HD3) has    17 elements
[DEBUG  ] Group     7 (            AP1) has    12 elements
[DEBUG  ] Group     8 (            ZN1) has     1 elements
[DEBUG  ] Group     9 (            ZN2) has     1 elements
[DEBUG  ] Group    10 (            WT1) has     3 elements
[DEBUG  ] Group    11 (            WT2) has     3 elements
[DEBUG  ] Group    12 (             NA) has     1 elements
[DEBUG  ] Group    13 (  GMXMMPBSA_LIG) has    32 elements
[DEBUG  ] Group    14 (            Cl-) has     6 elements
[DEBUG  ] Group    15 (        Protein) has  5007 elements
[DEBUG  ] Group    16 (      Protein-H) has  2481 elements
[DEBUG  ] Group    17 (        C-alpha) has   326 elements
[DEBUG  ] Group    18 (       Backbone) has   978 elements
[DEBUG  ] Group    19 (      MainChain) has  1305 elements
[DEBUG  ] Group    20 (   MainChain+Cb) has  1605 elements
[DEBUG  ] Group    21 (    MainChain+H) has  1619 elements
[DEBUG  ] Group    22 (      SideChain) has  3388 elements
[DEBUG  ] Group    23 (    SideChain-H) has  1176 elements
[DEBUG  ] Group    24 (    Prot-Masses) has  5007 elements
[DEBUG  ] Group    25 (    non-Protein) has 51737 elements
[DEBUG  ] Group    26 (            Ion) has     1 elements
[DEBUG  ] Group    27 (          Water) has 50019 elements
[DEBUG  ] Group    28 (            SOL) has 50019 elements
[DEBUG  ] Group    29 (      non-Water) has  6725 elements
[DEBUG  ] Group    30 ( Water_and_ions) has 50020 elements
[DEBUG  ] Group    31 (    protein_lig) has  5128 elements
[DEBUG  ] Group    32 (    rec_protein) has  5089 elements
[DEBUG  ] Group    33 (          envir) has 51616 elements
[DEBUG  ] Group    34 (            HD1) has    17 elements
[DEBUG  ] Group    35 (  GMXMMPBSA_REC) has  5095 elements
[DEBUG  ] Group    36 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  5127 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of ../peg_md_100/peg_md_center.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time    1.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] Last written: frame      0 time    0.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "There are only two kinds of programming languages: those people always bitch about and those nobody uses." (Bjarne Stroustrup)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 13: 'GMXMMPBSA_LIG'
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[ERROR  ] MMPBSA_Error 

The atom 6719 in the complex index is not found in the topology file. Please check that the files are consistent.

### Operating system

Linux

### Installation

AmberTools compilation + conda

**Comment by jjjjjqt** [comment]
@Valdes-Tresanco-MS @marioernestovaldes @BunnyRunnerX @LAndersen1

**Comment by Valdes-Tresanco-MS** [comment]
**Please do not make spam mentions without an explicit need. This is bad practice. We respond in our free time, so it may take time. #477 **
To resolve an issue you should consider reviewing previous issues and discussions in the group. This problem has been solved several times already. Could you consider creating a new index and check if this solves the problem? Commonly, the index file does not correspond to the structure (tpr), generating a new one using this structure as a reference can solve the problem (`gmx make_ndx -f md.tpr -o index.ndx`)
If not, please, check if the missing atom is in the topology and the complex as to supposed to be

**Comment by jjjjjqt** [comment]
> **Please do not make spam mentions without an explicit need. This is bad practice. We respond in our free time, so it may take time.** #477 To resolve an issue you should consider reviewing previous issues and discussions in the group. This problem has been solved several times already. Could you consider creating a new index and check if this solves the problem? Commonly, the index file does not correspond to the structure (tpr), generating a new one using this structure as a reference can solve the problem (`gmx make_ndx -f md.tpr -o index.ndx`) If not, please, check if the missing atom is in the topology and the complex as to supposed to be

I'm very sorry if my previous mention has caused you any inconvenience. I understand that everyone is taking time out of their precious free time to help each other. I tried again to generate the index file for the tpr using 'gmx make_ndx -f', but I'm still encountering this issue. I looked for the missing atoms, and they are in the topology file. Is there any other way to solve this?

**Comment by jjjjjqt** [comment]
Thank you very much, my questions have been resolved, and I appreciate your answers.

**Comment by gongshuai0606** [comment]
> Thank you very much, my questions have been resolved, and I appreciate your answers.

I've also encountered this，how did you solved it?
